//
// Created by parallels on 8/4/17.
//

#ifndef PRIVATEUTXO_CONSTANTS_H
#define PRIVATEUTXO_CONSTANTS_H

#define NOTE_PLAINTEXT_LEADING_BYTES 1
#define NOTE_PLAINTEXT_VALUE_BYTES 8
#define NOTE_PLAINTEXT_RHO_BYTES 32
#define NOTE_PLAINTEXT_R_BYTES 32

#define NOTE_PLAINTEXT_BYTES (NOTE_PLAINTEXT_LEADING_BYTES+NOTE_PLAINTEXT_VALUE_BYTES+NOTE_PLAINTEXT_RHO_BYTES+NOTE_PLAINTEXT_R_BYTES)

#define ENCRYPTION_AUTH_BYTES 16
#define CIPHERTEXT_BYTES (ENCRYPTION_AUTH_BYTES + NOTE_PLAINTEXT_BYTES)



#endif //PRIVATEUTXO_CONSTANTS_H
